name: Deploy Laravel Project on push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, exif, pcntl, bcmath
        ini-values: post_max_size=256M, upload_max_filesize=256M
        coverage: none

    - name: Install Composer Dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Generate Laravel key
      run: php artisan key:generate

    - name: Generate storage link
      run: php artisan storage:link

    - name: Set directory permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /


